#!/usr/bin/env bash
# This script transfers a file from the client to a server using scp

set -euo pipefail

if [ "$#" -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY" >&2
  exit 1
fi

path_to_file="$1"
ip="$2"
username="$3"
ssh_key="$4"

scp -o StrictHostKeyChecking=no -i "$ssh_key" "$path_to_file" "$username@$ip":~
